/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "PWMS1_1_aliases.h"
#include "PWMS1_1.h"
#include "PWMS2_2_aliases.h"
#include "PWMS2_2.h"
#include "Reloj.h"
#include "E1_aliases.h"
#include "E1.h"
#include "PWM_2.h"
#include "PWMS2_1_aliases.h"
#include "PWMS2_1.h"
#include "PWM_3.h"
#include "Reloj_1.h"
#include "led_aliases.h"
#include "led.h"
#include "Reloj_2.h"
#include "PWM_4.h"
#include "PWMS1_2_aliases.h"
#include "PWMS1_2.h"
#include "Reloj_3.h"
#include "UART.h"
#include "ADC1.h"
#include "Temperatura_aliases.h"
#include "Temperatura.h"
#include "UART_IntClock.h"
#include "ADC1_IRQ.h"
#include "ADC1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

