/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "PWM1.h"
#include "pin1_aliases.h"
#include "pin1.h"
#include "PWM.h"
#include "pin2_aliases.h"
#include "pin2.h"
#include "Clock_1.h"
#include "pin3_aliases.h"
#include "pin3.h"
#include "pin4_aliases.h"
#include "pin4.h"
#include "Clock_2.h"
#include "led_aliases.h"
#include "led.h"
#include "filtro1_aliases.h"
#include "filtro1.h"
#include "filtro2_aliases.h"
#include "filtro2.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

