/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "A1_aliases.h"
#include "A1.h"
#include "A0_aliases.h"
#include "A0.h"
#include "MUX.h"
#include "ADC.h"
#include "A2_aliases.h"
#include "A2.h"
#include "PWM.h"
#include "Clock_1.h"
#include "LED_aliases.h"
#include "LED.h"
#include "isrEnvio.h"
#include "isrRX.h"
#include "A3_aliases.h"
#include "A3.h"
#include "A4_aliases.h"
#include "A4.h"
#include "A5_aliases.h"
#include "A5.h"
#include "A6_aliases.h"
#include "A6.h"
#include "A7_aliases.h"
#include "A7.h"
#include "PGA.h"
#include "UART_IntClock.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

