# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Users\ESTEBAN\Documents\PSoC Creator\Proyecto_Temperatura\Lm35_7_segmentos.cydsn\Lm35_7_segmentos.cyprj
# Date: Thu, 02 Apr 2020 01:52:48 GMT
#set_units -time ns
create_clock -name {ADC_Ext_CP_Clk(routed)} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {Display1_InClock(routed)} -period 8333333.333333333 -waveform {0 4166666.66666667} [list [get_pins {ClockBlock/dclk_2}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_clock -name {ADC_Ext_CP_Clk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {UART_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 27 53} -nominal_period 1083.3333333333333 [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {ADC_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 39 77} [list [get_pins {ClockBlock/aclk_glb_0}]]
create_generated_clock -name {Display1_InClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 200001 400001} [list [get_pins {ClockBlock/dclk_glb_2}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for D:\Users\ESTEBAN\Documents\PSoC Creator\Proyecto_Temperatura\Lm35_7_segmentos.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Users\ESTEBAN\Documents\PSoC Creator\Proyecto_Temperatura\Lm35_7_segmentos.cydsn\Lm35_7_segmentos.cyprj
# Date: Thu, 02 Apr 2020 01:52:44 GMT
