/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SLED1_aliases.h"
#include "SLED1.h"
#include "LM35_aliases.h"
#include "LM35.h"
#include "Display1.h"
#include "Display1_Pins.h"
#include "Pulsador_aliases.h"
#include "Pulsador.h"
#include "ADC.h"
#include "SLED2_aliases.h"
#include "SLED2.h"
#include "UART.h"
#include "isrRx.h"
#include "Display1_InClock.h"
#include "Display1_LCD_ISR.h"
#include "Display1_Lcd_Dma_dma.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

